
- name: Install unzip
  apt:
    name: unzip
    state: latest
    update_cache: true

# TODO make a loop for list of apt package ?

- name: Ensure vikunja directory exists
  ansible.builtin.file:
    path: /app/vikunja
    state: directory
    mode: '0755'

- name: Download Vikunja api
  ansible.builtin.unarchive:
    src: https://dl.vikunja.io/api/0.20.2/vikunja-v0.20.2-linux-amd64-full.zip
    dest: /app/vikunja
    remote_src: yes
# TODO add a vraiable for the vikunja API version

# ADD https://dl.vikunja.io/api/0.20.2/vikunja-v0.20.2-linux-amd64-full.zip.asc ./
# RUN gpg --keyserver keyserver.ubuntu.com --recv FF054DACD908493A
# RUN gpg --verify vikunja-v0.20.2-linux-amd64-full.zip.asc vikunja-v0.20.2-linux-amd64-full.zip
# TODO add later GPG verification (need to install gpg as an APT package)


- name: deploy systemd service unit for api
  template:
    src: "systemd.j2"
    dest: "/etc/systemd/system/vikunja.service"
    mode: 0755

- name: "Force systemd to reread configs"
  systemd:
    daemon_reload: true

- name: "Start and Enable (always started after reboot) service vikunja"
  service:
    name: "vikunja"
    enabled: true
    state: "started"
